export const RN_API = {
    SET_COPY: "SET_COPY",
    SET_FILENAME: "SET_FILENAME",
    GET_FILENAME: "GET_FILENAME",
    GET_FILE: "GET_FILE",
    SHARE_FILE: "SHARE_FILE",
    GET_FILE_LIST: "GET_FILE_LIST",
    CREATE_FILE: "CREATE_FILE",
    SET_FILE: "SET_FILE",
    DELETE_FILE: "DELETE_FILE",
} as const
